config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :invitations
  resources :events
  devise_for :users 
  root 'events#index'
  get '/creators/info'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitation, dependent: :destroy
  has_many :attendees, through: :invitation, source: :user

  scope :past, -> { where('start_date < ?', Date.today) }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }

  validates :name, :start_date, :end_date, :location, :description, :creator_id, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/invitation_list.rb
class InvitationList < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event', dependent: :destroy
  has_many :invitation
  has_many :attended_event, through: :invitation, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def info
    @created_events = current_user.created_events
    @past_events = current_user.attended_event.past
    @upcoming_events = current_user.attended_event.upcoming
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /events or /events.json

  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @invitation = Invitation.new
  end

  # GET /events/new
  def new
    @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @event = current_user.created_events.find_by(id: params[:id])
    redirect_to events_path, notice: 'Not Authorized To Edit Event' if @event.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :location, :description, :user_id)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  # GET /invitations/1 or /invitations/1.json
  def show; end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # POST /invitations or /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)
    isthere = Invitation.where('user_id= ? AND event_id= ?', @invitation.user_id, @invitation.event_id)
    if !isthere.ids[0].nil?
      redirect_to events_path, notice: 'You Already in the list.'
    else
      @invitation.save
      redirect_to events_path, notice: 'Invitation was successfully created.'
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy
    redirect_to invitations_url, notice: 'Invitation was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invitation_params
    params.require(:invitation).permit(:user_id, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @created_events = current_user.created_events
        @past_events = current_user.attended_event.past
        @upcoming_events = current_user.attended_event.upcoming
    end
    private 
    def event_params
        params.require(:event).permit(:email, :encrypted_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/creators/info.html.erb
<h1>Created events</h1>
<div class="d-flex justify-content-between flex-wrap">
     <%@created_events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header">
           <h5 class="card-title"><%= event.name %></h5>
           <p class="card-title"><%= event.creator.email.split('@')[0] %></p>
        </div>
        <div class="card-body">
          <p class="card-text">Des:<%= event.description %></p>
          <p class="card-text">Loc:<%= event.location %></p>
          <span class="card-subtitle text-muted">St: <%= event.start_date%></span> | 
          <span class="card-subtitle text-muted">End: <%= event.end_date %></span>
          <%= link_to 'Show', event,class:'card-link' %>
          <%= link_to 'Edit', edit_event_path(event),class:'card-link' %>
          <%= link_to 'Destroy', event,class:'card-link', method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
      </div>
      <% end %>
    </div>

    <h1>upcoming events</h1>
    <div class="d-flex justify-content-between flex-wrap">
     <%@upcoming_events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header">
           <h5 class="card-title"><%= event.name %></h5>
           <p class="card-title"><%= event.creator.email.split('@')[0] %></p>
        </div>
        <div class="card-body">
          <p class="card-text">Des:<%= event.description %></p>
          <p class="card-text">Loc:<%= event.location %></p>
          <span class="card-subtitle text-muted">St: <%= event.start_date%></span> | 
          <span class="card-subtitle text-muted">End: <%= event.end_date %></span>
          <%= link_to 'Show', event,class:'card-link' %>
          <%= link_to 'Edit', edit_event_path(event),class:'card-link' %>
          <%= link_to 'Destroy', event,class:'card-link', method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
      </div>
      <% end %>
    </div>

<h1>past events</h1>
    <div class="d-flex justify-content-between flex-wrap">
     <%@past_events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header">
           <h5 class="card-title"><%= event.name %></h5>
           <p class="card-title"><%= event.creator.email.split('@')[0] %></p>
        </div>
        <div class="card-body">
          <p class="card-text">Des:<%= event.description %></p>
          <p class="card-text">Loc:<%= event.location %></p>
          <span class="card-subtitle text-muted">St: <%= event.start_date%></span> | 
          <span class="card-subtitle text-muted">End: <%= event.end_date %></span>
          <%= link_to 'Show', event,class:'card-link' %>
          <%= link_to 'Edit', edit_event_path(event),class:'card-link' %>
          <%= link_to 'Destroy', event,class:'card-link', method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
      </div>
      <% end %>
    </div>

app/views/events/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/events/_form.html.erb
<div class="card-body">
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control'%>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description,class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary mt-2' %>
  </div>
<% end %>

</div>

app/views/events/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Events', events_path,class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
            <%=link_to current_user.email.split("@")[0],'/creators/info',class:'nav-link'%>
            <%= link_to 'new event', new_event_path,class:'nav-link'%>
            <%= link_to 'edit account',edit_user_registration_path,class:'nav-link'%>
            <%= link_to 'sign out',destroy_user_session_path, method: :delete,class:'nav-link'%>
        <%else%>
            <%= link_to 'sign in',new_user_session_path,class:'nav-link'%>
            <%= link_to 'sign up',new_user_registration_path,class:'nav-link'%>
        <%end%>
      </ul>
 
    </div>
  </div>
</nav>

app/views/events/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Editing Event</h4>
  </div>
  <%= render 'form', event: @event %>
</div>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>UpComing Events</h1>
<div class="d-flex justify-content-between flex-wrap">
     <% @events.upcoming.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header">
           <h5 class="card-title"><%= event.name %></h5>
           <p class="card-title"><%= event.creator.email.split('@')[0] %></p>
        </div>
        <div class="card-body">
          <p class="card-text">Des:<%= event.description %></p>
          <p class="card-text">Loc:<%= event.location %></p>
          <span class="card-subtitle text-muted">St: <%= event.start_date%></span> | 
          <span class="card-subtitle text-muted">End: <%= event.end_date %></span>
          <%= link_to 'Show', event,class:'card-link' %>
          <%= link_to 'Edit', edit_event_path(event),class:'card-link' %>
          <%= link_to 'Destroy', event,class:'card-link', method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
      </div>
      <% end %>
      </div>
    <h1>Past Events</h1>
    <div class="d-flex justify-content-between flex-wrap">
     <% @events.past.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header">
           <h5 class="card-title"><%= event.name %></h5>
           <p class="card-title"><%= event.creator.email.split('@')[0] %></p>
        </div>
        <div class="card-body">
          <p class="card-text">Des:<%= event.description %></p>
          <p class="card-text">Loc:<%= event.location %></p>
          <span class="card-subtitle text-muted">St: <%= event.start_date%></span> | 
          <span class="card-subtitle text-muted">End: <%= event.end_date %></span>
          <%= link_to 'Show', event,class:'card-link' %>
          <%= link_to 'Edit', edit_event_path(event),class:'card-link' %>
          <%= link_to 'Destroy', event,class:'card-link', method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
      </div>
      <% end %>
      </div>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New Event</h1>
  </div>
  <%= render 'form', event: @event %>
</div>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Description</th>     
      <th>Creator</th> 
    </tr>
  </thead>
  <tbody>
    <tr>
      <th><%= @event.name %></th>
      <td><%= @event.start_date %></td>
      <td><%= @event.end_date %></td>
      <td><%= @event.location %></td>
      <td><%= @event.description %></td>
      <td><%= @event.creator.email.split('@')[0] %></td>
    </tr>
    
      
  </tbody>
</table>
<%= link_to 'Edit', edit_event_path(@event),class:'btn btn-secondary' %> 
<%= link_to 'Back', events_path,class:'btn btn-secondary' %>


<div class="list-group w-50 mt-3">
<a class="list-group-item list-group-item-action active" aria-current="true">
    invitation list
  </a>
 <%@event.attendees.each do |attendee|%>
  <a href="#" class="list-group-item list-group-item-action"><%=attendee.email.split('@')[0]%></a>
  <%end%>


      <%= form_with(model: @invitation) do |form| %>
            <div class="feild">
              <%= form.number_field :user_id ,value:current_user.id,type: :hidden%>   
            </div>
            <div class="feild">
              <%= form.number_field :event_id,value:@event.id,type: :hidden%>  
            </div>    
            <div class="actions">
              <%= form.submit "Enroll",class: 'btn btn-primary'%>
            </div>
        <% end %>
</div>

app/views/invitations/_form.html.erb
<%= form_with(model: invitation) do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="feild">
    <%= form.label :user_id%>
    <%= form.number_field :user_id%>   
  </div>
  <div class="feild">
    <%= form.label :event_id%>
    <%= form.number_field :event_id %>  
  </div>    
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>PrivateEvents f</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%=render 'events/nav'%>
      <div class="container">
        <%if notice%>
          <%=render 'events/alert'%>
        <%end%>
        <%= yield %>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>